### ISSUE TITLE
build-test-staging-prod pipeline image is wrong

### ISSUE THREAD

**Issue by p2well** [MicrosoftDocs/pipelines-multistage#5]
Pipeline image `res/build-test-staging-prod.png` is wrong. The last stage should be called 'prod' and not 'staging' again.

![image](https://user-images.githubusercontent.com/15157960/57839997-086c7180-77c8-11e9-9c62-66a848bb64f5.png)

**Comment by matthewisabel** [comment]
Good flag, we'll fix it up

**Comment by adrianmg** [comment]
Thanks, @p2well. We just fixed it!
