### ISSUE TITLE
No way to stop in between stage

### ISSUE THREAD

**Issue by gotosatheesh** [MicrosoftDocs/pipelines-multistage#8]
Hi Team

build-test-staging-prod, In this example all the stages are executing one by one immediately, we need manual user testing after deploying to test and then deploy to prod, so how do we stop in between stages and start the production deployment when needed.seems like all your example is not addressing that and the example are not real world scenarios without that

**Comment by matthewisabel** [comment]
This will be available soon. When it is we'll provide some more documentation on how to use manual approvals.

**Comment by epernst** [comment]
I where really looking forward to these new multi-stage pipelines. But without the ability to have manual approvals or other of the gating features between the stages, then its really not that useful.

So would love to know if you have any ETA on when this will be in the preview?

**Comment by Rick-van-Dam** [comment]
Without this the value of multi stage yml's is meager at best.

What I want is that the stop can also be made conditional. For instance:
- Every commit on master should be deployed
- Commits on other branches can be deployed optionally.

This should be possible if a way to stop between stages was added and it was possible to make that stop conditional.

**Comment by epernst** [comment]
@Barsonax  You can make it conditional (condition works in Yaml), but you cannot have any manual interactions/approvals in your pipeline.

**Comment by Rick-van-Dam** [comment]
But what I want is conditional manual approvals

**Comment by epernst** [comment]
Wondering if this is what we are looking for:
https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-155-update#approvals-in-multi-stage-yaml-pipelines

I just cannot see how to use it, or if it has not been made available yet.
